server:
  port: "${submodule.server.store.port}"
spring:
  cache:
    redis:
      time-to-live: PT1m
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8888/realms/master
        registration:
          yandex-store:
            provider: keycloak
            authorization-grant-type: client_credentials
            client-id: yandex-store
            client-secret: mxmPrWQqu1zEz74US6P1gGsUBFSef9pR
            scope:
              - profile
            client-authentication-method: client_secret_post