server:
  port: 0
spring:
  webflux:
    base-path: /intershop
  data:
    r2dbc:
      schema: public
  liquibase:
    change-log: classpath:/db/changelog/rootChangeLog.xml
    default-schema: public
    parameters:
      schemaName: public
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8888/realms/master
submodule:
  server:
    payment:
      port: 7070
      host: localhost
    store:
      port: 9090
      host: localhost