server:
  port: 0
spring:
  data:
    r2dbc:
      schema: public
  liquibase:
    change-log: classpath:/db/changelog/rootChangeLog.xml
    default-schema: public
    parameters:
      schemaName: public