server:
  port: 9090
  servlet:
    context-path: /intershop

spring:
  application:
    name: intershop
  datasource:
    driver-class-name: org.postgresql.Driver
    password: yandex
    username: yandex
    url: jdbc:postgresql://localhost:5438/yandex
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  liquibase:
    change-log: classpath:/db/changelog/rootChangeLog.xml
    default-schema: intershop
    parameters:
      schemaName: intershop
management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
    liquibase:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    liquibase: INFO

image-dir: images
app-base-dir: user.dir
clear-upload-dir: false
default-image-path: static/default_image.png