server:
  port: 9090
  servlet:
    context-path: /intershop

spring:
  application:
    name: intershop
  r2dbc:
    url: r2dbc:postgresql://localhost:5438/yandex
    password: yandex
    username: yandex
    pool:
      enabled: true
      initial-size: 10
      max-size: 50
      max-idle-time: 30s
      max-life-time: 10m
      validation-query: SELECT 1
  liquibase:
    change-log: classpath:/db/changelog/rootChangeLog.xml
    default-schema: intershop
    parameters:
      schemaName: intershop
management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
    liquibase:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    org.example: DEBUG
    liquibase: INFO