server:
  port: 0
spring:
  liquibase:
    default-schema: public
    parameters:
      schemaName: public
  jpa:
    properties:
      hibernate:
        default_schema: public
        show_sql: false