openapi: 3.0.3
info:
  title: Payment API
  version: 1.0.0
  description: API для получения баланса и оплаты товара
paths:
  /balance:
    get:
      summary: Получение суммы баланса на счете
      responses:
        '200':
          description: Сумма баланса
          content:
            application/json:
              schema:
                type: string
                format: decimal
                description: Сумма на счете
                pattern: '^\d+\.\d{2}$'
                example: "150.00"
    post:
      summary: Списание суммы с баланса на счете
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: string
              format: decimal
              description: Сумма на счете
              pattern: '^\d+\.\d{2}$'
              example: "150.00"
      responses:
        '200':
          description: Успешное списание суммы с баланса
          content:
            application/json:
              schema:
                type: string
                format: decimal
                description: Сумма на счете
                pattern: '^\d+\.\d{2}$'
                example: "150.00"
        '422':
          description: Недостаточно средств на балансе
          content:
            application/json:
              schema:
                type: string
                example: "Недостаточно средств на балансе. Сумма баланса 500.00"
components:
  schemas:
    Account:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: Первичный ключ
          example: 1
        balance:
          type: string
          format: decimal
          description: Сумма на счете
          pattern: '^\d+\.\d{2}$'
          example: "150.00"